#+TITLE:    TopCoder SRM 488: TheBoring Store
#+AUTHOR:    Ani
#+EMAIL:     anirudhsaraf@gmail.com
#+STARTUP: showall indent
#+STARTUP: hidestars
#+INFOJS_OPT: view:info toc:t
#+OPTIONS: H:2 num:t toc:t
#+BEGIN_HTML
---
layout: post
title:  TopCoder SRM 488 The BoringStore (Working Draft)
tags: TopCoder, Advanced Math
---
#+END_HTML

*** Problem Statement: [[http://www.topcoder.com/stat?c=problem_statement&pm=11194&rd=14241][TheBoredomDivTwo]] (TC-Registration) [[http://pastehtml.com/view/1c0se0l.html][TheBoredomDivTwo]]
*** Solution: [[http://gist.github.com/709104][TheBoredomDivTwo.cxx]]
*** Used As: Division II Level Two
*** Categories: Advanced Math, Encryption/Compression

* Solution :
For people new to TopCoder (like me) I think it is natural to
feel overwhelmed when you first read the problem statement. The
important thing is to let that feeling pass, re-read the problem and
not give up. 

Step 1) Feel overwhelmed 
*insert picture here* 

Now that the initial feeling has passed, lets re-read the problem
statement and understand it. Do not think of how you will solve it.I
repeat - do not think in terms of coding yet. The best thing to do is
print out the problem statement and sit with a pen and paper. Under no
circumstance should you have your *emacs* window open! Since my primary
goal is not competing against other contestants but to improve my
coding, algorthimic and thinking skills I spend a significant amount
of my time reflecting on *how I am doing things*. <insert another picture>

Alright enough commentary. Time to dissect the problem statement
now. As I have stated <earlier> it is important to get to a point where
you understand the problem enough to rephrase it. If you are new, you
should actually try writing the problem in as few and simple words as
you can ( have a math background does help here :) ). 

So lets make an attempt at rephrasing: Given two string X and Y, find
the longest possible string such that A + C = B + D (or A+D=B+C) where A,B are
non-overlapping contiguous substrings of X and C,D are substrings of
Y. I cannot stress enough the importance of rephrasing the
problem. While the long winding TopCoder descriptions are important
for understanding - the succint version is important to ensure that
you have understood the problem! While my version is not
completely correct and misses some finer points ( like how the
'longest possible string' is defined), it gives me a good sense of my
understanding of the problem. So stop, and if re-read and understand
the problem till the rephrased version makes sense to you. 
